ctubio/Krypto-trading-bot

src/share/models.ts
For Bitfinex new markets: SAN/USD, SAN/BTC SAN/ETH starting 12/07/17
=> Adding Santiment (SAN)

dist/README.md
Because of the nature how Docker works, the SQLite database will be lost if the container get recreated.
Mounting a local folder to `/data` inside the container will ensure that the database gets preserved.
=> bind-mount external folder for persistence

src/server/qe.h
If TBP is 0 and the user has also set pDiv to 0, the bot continually buys and sells 1 trade. This change prevents the bot from buying.
=> Prevent bot buying if both TBP and pDiv are 0

src/server/qe.h
Hey Charles,
this one is for all the unlucky traders like me...
when K burned up all the money and the funds are less than minSize at least bitfinex throws lots of those errors: 
> Invalid order: not enough exchange balance for 0.01 ETH/USD
because there is no validation if the wallet is equal or higher than minSize.
I propose to ged rid of these errors and better route them to the cli with this PR.
Don't know if it´s the best way to do or the right position in the code
=> Fix Bitfi not enough exchange balance error

src/client/main.ts
This PR fixes an Error with safari and navigator.hardwareConcurrency. 
Safari did not return the value of cores and for that reason safari unsers can use only one mining thread.
This patch just sets up a default value by 8 if the browsers did not return real values .
=> Fix an issue with XMR miner threads on Safari

src/server/qp.h
Fixes an issue with withPing and withPong accepting only interger values in the GUI.
Now the float values are no longer cut to integer on serve side
=> Fix Ping&Pong width with decimals

src/server/qe.h
This fix prevents HamelinRat to generate odd quotes when no position in the order book is found to place a right quote.
=> Fix HamelinRat error generating minTix quotes

src/server/gw.h
The problem here is that the price precision of the ewma is also limited, making results unprecise for low value asset markets.
Example DAT/BTC market: ewma is only defined by 3 significative results.
=> Ewma precision issue: Reverting

Vagrantfile
Basic Vagrant setup with Ubuntu 16.04 (xenial) box to be used for building & developing.
Install [VirtualBox](https://www.virtualbox.org/wiki/Downloads) and [vagrant](https://www.vagrantup.com/downloads.html)
In the root K  dir call: `vagrant up`
This will download ubuntu box, and configure it with g++6 as the default compiler
Then do:  `vagrant ssh`
and you're in the home dir of a Ubuntu box, with Krypto-trading-bot dir right there waiting to be make'd
Next step would be to use an Ubuntu desktop box, provision it with an IDE (I imported K in eclipse really easy) to get a good C++ dev env in no time
=> Add Vagrant with Ubuntu 16.04 box

src/server/mg.h
Hope that it helps to resolve #474 
btw. i have seen that the recalculation routine recalls only if there are enough values available. My attempt was to use the very last available value for the missing ones... won't we give that a try?
=> Fix wrong EWMA recalculation

src/www/index.html
When putting behind a reverse proxy under a context path, static files will not load correctly. This fixes the issue.
Example path:
```
https://www.example.com/trading/for/fun/
```
I needed this commit to run the server and to have it be useful to me.
[many thanks for the info''¡ feel free to restart it]
Thank you!
=> Add support for reverse proxy

src/client/stats.ts
Popup boxes on stat charts now show the description of the chart.
Helping make a more selfexplanatory UI. I hope.
=> Added description of chart to popup

src/server/qe.h
Hello everyone,
First of all, thank you @ctubio for maintaining this bot which is very fun to play with.
I’ve been running it for a few days to test its capabilities, and even though I haven’t been able to generate much profit due to my lack of experience in this domain, it seems very promising.
I opened this PR because I noticed that the range option of the AK-47 mode doesn’t exactly matches its description in the manual.
It seems to me that the range should only affect the distance between each bid bullet, though it is currently also affecting the first bid because its value is biased by the default value of `AK47Inc = 1`.
The fix was simply to set the default value of `AK47Inc` to 0 to prevent affecting the first bid and reset it to this value after computing the other bullets.
I hope …
=> AK47 range should not impact first quote value

README.md
I just noticed discord invite links expire after 1 day by default, I changed the setting to never so I apologize for anyone trying to join yesterday when it was expired. This new link should work now forever :).
=> Never expiring link

etc/Dockerfile
Current dockerfile broken
You are deleting apt cache and call later apt install from "make docker" what causes error that packages not found.
So I moved apt cache deletion to later stage after "make docker" and now everything works fine
=> Fix Dockerfile apt update issue

Makefile, etc/Dockerfile
Sed was chomping too much out of K.sh based on recent changes to the file.
Add new ENV variable to Dockerfile to specify the binary.
Also build off a node-8-buster base.
Source for that docker-hub image here: https://github.com/OverlordQ/8-buster
PR/Donate address: 3BxPeFskRwRgSePqKLoCXDCheTX4MzyRsQ
=> Fix Docker build

src/lib/Krypto.ninja-bots.h
This enables [SQLite WAL mode](https://www.sqlite.org/wal.html) which makes disk usage much, much less.
A side effect is that the database is now stored in 2-3 files instead of just one.  This may be undesired.
=> enable WAL mode for nonmem database to reduce io

src/bin/trading-bot/client/trades.ts
The old UI code determines whether to mark matched trades as a buy or sell based on the price.  This gives the wrong result for losses.  This change marks losses correctly.
Although the code could be adjusted to never produce pairs with losses, given that this may happen occasionally due to some rare circumstance, it is important for it to be visible to the user.
=> Show losses correctly in UI

src/lib/Krypto.ninja-data.h
I inspected the applyBestWidth function and it looks to me like these changes are warranted.  Agree / disagree?
- depth comparison didn't continue if depth was equal.  This wouldn't skip zero-valued entries if those happened for some reason.
- loop break is inside the price check.  This could cause the next loop to move the picked price beyond the best width.  It seems to me if the price check fails, we're already at the best width.
=> BestWidth Fixes

src/lib/Krypto.ninja-bots.h
Helps to let users adjust fees when the binary lib hasn't integrated fee changes yet.
=> add cmdline args to set maker and taker fees

src/lib/Krypto.ninja-data.h
Sometimes my buys or sells are just _empty_ with no explanation.
I passed --debug and found that APR was pricing pongs on the wrong side of the market when it had moved more than pongwidth since a ping.
Patch attempts to fix this so such pongs are placed.
EDIT: I've set the limit properly now.  It's as tight as possible without allowing for crossing.
=> prevent APR-adjusted orders from crossing the market

src/lib/Krypto.ninja-data.h
This is a squash, rebase, and fixup for #919.
- account for maker fee at all steps
- don't attempt to spend held balances ('total' becomes 'amount')
- remove some redundant checks and truncations
=> Fixes for wallet size limits.

src/lib/Krypto.ninja-data.h, test/units.h
This changes the pong matching behavior to prevent any that would be losses, even when AveragePingFair for example is used.
I also added a quick check to make sure the diff is greater than the fee.  This might be changed when fees are more fully implemented in the mOrderFilled structure.
Since there are no longer negative Kdiffs in the testing scenario, I also added the test commit in my crosspongs-plusbug branch from https://github.com/ctubio/Krypto-trading-bot/pull/911#issuecomment-480233698 .
=> Prevent unprofitable pong matches

src/lib/Krypto.ninja-apis.h, src/lib/Krypto.ninja-bots.h
I found on Poloniex often trades for less than a dollar will be rejected.  Being able to tweak minSize let me work around this for now, so that my smaller trades will be large enough to be accepted.
Unfortunately I could only see the error by packet-logging.  It would be really great for the private lib to return error messages (#920).
=> Allow for custom minsize if exchange data is stale/wrong.

src/bin/trading-bot/client/main.ts, src/lib/Krypto.ninja-user.h
=> Solve #944

doc/MANUAL.md, src/bin/trading-bot/client/main.ts, src/bin/trading-bot/client/models.ts, src/bin/trading-bot/client/pair.ts, src/lib/Krypto.ninja-user.h, test/units.h
This is a resubmission of my PR to add an option to tune how order size percentages are taken.
When `%` mode is enabled, an `orderPctTot` option appears providing to set how to select size percentages.
The different options provide for taking the percentages of the balances in different ways, such that how the balance evolves is different.  For example, you can have bid sizes for USD shrink very tiny when you have already sold most of your USD.  This lets you keep trading a little when far from the TBP.
The TBPSide option tunes the parameters such that each size reaches 0 at the `pdiv` extents, and they are equal at `TBP`.
=> Add percentage options to adjust order size based on TBP.

src/bin/trading-bot/trading-bot.data.h
The previous TBP limiter was clipping to a region of TBP instead of mapping to it. For example if the tbp limits are 10% to 20%, if the TBP engine calculated 0%, 5%, 50% and 100% the old code clipped those to 10, 10, 20, 20. 
This update converts this clipping to mapping. The above values are now accordingly mapped to 10%, 10.5%, 15% and 20%.
=> Fix TBP limit

etc/Dockerfile
Currently, building on docker takes 
```
market-maker: 991 MBs
overlordq/8-buster: 826 MBs
```
Changing the base image will reduce this to
```
market-maker: 400 Mbs
debian:buster-slim: ~26.47
```
I'm not sure why you kept that image, it hasn't been updated for two years and the original Dockerfile [can't be found](https://github.com/OverlordQ/8-buster).
Hope this PR is helpful!
=> Docker container goes brrrr (slim down image size)
