src/server/statistics.ts

As it was updating  Ewma protection only if > 1e-3, meaning that it would not or rarely update for BTC and ETH denominated markets.
Please ignore if I'm wrong :)

Remove useless and potential harmful code

---

src/server/qe.h

Fixes the issue that APR never switched off once switched to Bid/Sell mode.

Fix APR never gets back off

---

src/client/orders.ts
src/client/trades.ts

Decided to make some small cosmetic improvements for UI.
Now it's much better to view orders and trades. This commit solve the problem when you don't see trades/orders details, like value and price.

Added auto width fit for columns in orders/trades grid.

---

src/server/qe.h

Hey Charles,
Im almost 99% sure that this one line has to be at another Position to correctly switch off sideAPR.
(hmm i have a sense of a deja vue)

Fix Error switching off sideAPR

---

src/client/main.ts
src/client/models.ts
src/client/pair.ts
src/client/trades.ts
src/server/km.h
src/server/qe.h
src/server/qp.h

Hi Charles, 
here is the result of the last days research improving K. I did not yet tested it deeply and its all beta status. 
What i did:
- Each quoting mode has its own piece of code just to better find errors and make the code if-less
- An Idea @Camille92 mentioned here #317 I split the quoting modes into modes & safeties (not 100% finished because of hamelinrat)
- Also mentioned by @Camille92: the bullet range is now usable with percents (percent of the "value")
- i added the APRmultiplier option the GUI (it was almost everything in the code already and i think it can be helpful tu have)
-  removed some minor & major bugs
if you find things of that stuff helpful, i am happy if it finds its way into K 
btw. i've see a threeheadedmonkey beacause of a new value in the db, i had to …

Improve and bugfix quoting engine

---

src/client/main.ts
src/client/models.ts
src/client/stats.ts
src/server/ev.h
src/server/km.h
src/server/mg.h
src/server/qe.h
src/server/qp.h

**PURPOSE:**
- Stop selling or buying on trends with predefined trend stregth threshold.
- Trend is defined through EWMA Micro+Ultra periods by formula: STRENGTH = - ( ( mgEwmaSM - mgEwmaSU ) / mgEwmaSM ) * 1000
- EWMA strength is presented on chart
**SETTINGS:**
- EWMA Micro Period (12)
- EWMA Ultra Period (3)
- Stregth Threshold (2) - start TBP held when strangth more then +2 or less then -2

Added EWMA Trend protection.

---

MANUAL.md
src/server/qe.h
src/server/qp.h

Fixes an Error that the width is not respected correctly on ask sides at quoting modes Top and Join.

Fix error Top & Join respect Width

---

MANUAL.md
package.json
src/client/main.ts

Updates the manual with the new super trades options and fixes some settings confusion.
And brings back jQuery because without that make bundle throws an error

Update Manual for Super Trades 

---

.gitignore
MANUAL.md
src/client/main.ts
src/client/market-trades.ts
src/client/trades.ts
src/client/wallet-position.ts

1. Added total amount counters for base and quote currencies (Available + Held)
For example, I always interested see in UI total amount of pair base currency and quote (Available + Held). Compiled example:
2. Added fast features to dialog "Submit Order":
- toggle Bid / Ask by click Side:;
- add top values of bidSize, bidPrice, askPrice, askSize according to Side and by clicking Price:, Size:.
Help to add some basis data (Like price and trade size) faster. If you try write it manually or with Ctrl+c \ Ctrl + v you can lost time and price point.
3. Resalable columns in trades table. (Some browsers cut values and you cant see end price values).
Before:
After:
4. MANUAL.md replace K.js -> K.sh

UI Features

---

MANUAL.md

Fixing result of bad search & replace

---

src/client/main.ts

Fix console spam issue with augury extension

---

README.md

I've been carefully reading your documentation for the last few days to learn how to use K, and I thought you might appreciate some improvements to it. 
Your documentation overall has been much better than other trading bots I've looked at. There were just some parts that confused me while I was learning. Now that I understand K pretty well, I was able to clarify the README.
I hope you find the changes helpful. Let me know if I misunderstood what you meant anywhere.
[thanks for the info'']

README.md clarity improvements

---

src/client/main.ts

Information from MANUAL.md copied to tooltips for settings parameter.
So you have a handy "what was that again" information on the UI

Added Tooltips to settings parameter

---

src/client/main.ts
src/client/models.ts
src/server/cf.h
src/server/km.h
src/server/mg.h
src/server/qe.h

Hi Carles,
here is (hopefully) the missing functionality for the EwmaTrendProtection:
- Store values in the DB
- Recall values on Start/Restart
- Recalculate values when user-parameters change
It is not deeply tested. Please use with caution and please give me a feedback if something works wrong.

Missing Functionality to EwmaTrend

---

src/client-2d/main.ts

Reduces both minimum value & step size for pingWidth% & pongWidth% parameters from 0.01 to 0.001

Reduce minimum pingWidth% & pongWidth% from 0.01 to 0.001

---

doc/MANUAL.md
src/include/Krypto.ninja-data.h
src/trading-bot/client/main.ts

Adds a bestWidthSize parameter to allow ignoring small orders in the book. 
https://github.com/ctubio/Krypto-trading-bot/issues/750
https://github.com/ctubio/Krypto-trading-bot/issues/810
Just trying out my first pull request :)

Best width size

---

doc/MANUAL.md

Hi! Thanks for your work on this repo. I will try and contribute, I will start with the Manual. I went through the parameters in the Manual and corrected a few things.

Updated Readme

---

src/lib/Krypto.ninja-apis.h
src/lib/Krypto.ninja-data.h

short for time but sharing this, questions / concerns welcome

quick fix for depletion issue discussed on irc

---

src/bin/trading-bot/client/stats.ts

Fix: updateCharts to check for ewma before checking property.

fix #1015 

---

src/bin/trading-bot/client/main.ts
src/bin/trading-bot/client/market-quoting.ts
src/bin/trading-bot/client/orders.ts
src/bin/trading-bot/client/trade-safety.ts
src/bin/trading-bot/www/sass/bootstrap-theme-dark.scss
src/bin/trading-bot/www/sass/bootstrap-theme.scss
src/bin/trading-bot/www/sass/bootstrap.scss

Hi!
I have made some UI improvements! please review and let me know your opinion :) 
Here are the notable changes made:
* Quoting Parameter input area UI improved.
* Safety & Quoting parameters display area improved.
* Consistancy of fonts, font-sizes, colors.
* Button outlines removed, unused classes removed from .ts files.
* All these changes applied to both dark, and light version.
Here is how it looks [Dark UI](https://imgur.com/a/9XwElK8) & [light UI](https://imgur.com/OiRdeAP).

Web UI Updates.
